### ISSUE TITLE
Fix latest default image: `/bin/sh: /usr/libexec/s2i/run: No such file or directory`

### ISSUE THREAD

**Issue by MEllis-github** [rh-ecosystem-edge/console-plugin-nvidia-gpu#28]
### Overview
Following the steps in the [quickstart](https://github.com/rh-ecosystem-edge/console-plugin-nvidia-gpu#quickstart), deployment fails due to the console-plugin pod encountering `/bin/sh: /usr/libexec/s2i/run: No such file or directory`, running [CMD](https://github.com/rh-ecosystem-edge/console-plugin-nvidia-gpu/blob/14d797131de5271738f22b6d665714cf4d9361be/Dockerfile#L17). The image is quay.io/cilium/alpine-curl:v1.4.0; `helm --debug` output is included below.

### Steps
```
bash-3.2$ helm repo add rh-ecosystem-edge https://rh-ecosystem-edge.github.io/console-plugin-nvidia-gpu
"rh-ecosystem-edge" already exists with the same configuration, skipping
bash-3.2$  helm repo update
Hang tight while we grab the latest from your chart repositories...
...
...Successfully got an update from the "rh-ecosystem-edge" chart repository
...
Update Complete. ⎈Happy Helming!⎈
```
```
bash-3.2$ helm install -n nvidia-gpu-operator console-plugin-nvidia-gpu rh-ecosystem-edge/console-plugin-nvidia-gpu
NAME: console-plugin-nvidia-gpu
LAST DEPLOYED: Tue May 24 13:49:45 2022
NAMESPACE: nvidia-gpu-operator
STATUS: deployed
REVISION: 1
NOTES:
View the Console Plugin NVIDIA GPU deployed resources by running the following command:

$ kubectl -n nvidia-gpu-operator get all -l app.kubernetes.io/name=console-plugin-nvidia-gpu

Enable the plugin by running the following commands:

# check if a plugins field is specified
$ oc get consoles.operator.openshift.io cluster --output=jsonpath="{.spec.plugins}"

# if not, then run the following to enable the plugin
$ kubectl patch consoles.operator.openshift.io cluster --patch '{ "spec": { "plugins": ["console-plugin-nvidia-gpu"] } }' --type=merge

# if yes, then run the following to enable the plugin
$ kubectl patch consoles.operator.openshift.io cluster --patch '[{"op": "add", "path": "/spec/plugins/-", "value": "console-plugin-nvidia-gpu" }]' --type=json
```

```
bash-3.2$ kubectl -n nvidia-gpu-operator get all -l app.kubernetes.io/name=console-plugin-nvidia-gpu
NAME                                             READY   STATUS   RESTARTS      AGE
pod/console-plugin-nvidia-gpu-5fddcdbf54-fkkjs   0/1     Error    2 (19s ago)   23s

NAME                                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/console-plugin-nvidia-gpu   ClusterIP   172.30.228.60   <none>        9443/TCP   24s

NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/console-plugin-nvidia-gpu   0/1     1            0           24s

NAME                                                   DESIRED   CURRENT   READY   AGE
replicaset.apps/console-plugin-nvidia-gpu-5fddcdbf54   1         1         0       24s
```
```
bash-3.2$ oc logs pod/console-plugin-nvidia-gpu-5fddcdbf54-fkkjs
/bin/sh: /usr/libexec/s2i/run: No such file or directory
```

### Additional info.
helm --debug output
```
client.go:128: [debug] creating 3 resource(s)
NAME: console-plugin-nvidia-gpu
LAST DEPLOYED: Tue May 24 13:52:38 2022
NAMESPACE: nvidia-gpu-operator
STATUS: deployed
REVISION: 1
USER-SUPPLIED VALUES:
affinity: {}
fullnameOverride: ""
image:
  pullPolicy: Always
  repository: quay.io/edge-infrastructure/console-plugin-nvidia-gpu
imagePullSecrets: []
nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}
tolerations: []

COMPUTED VALUES:
affinity: {}
fullnameOverride: ""
image:
  pullPolicy: Always
  repository: quay.io/edge-infrastructure/console-plugin-nvidia-gpu
imagePullSecrets: []
nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}
tolerations: []

HOOKS:
---
# Source: console-plugin-nvidia-gpu/templates/tests/test-plugin-service.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "console-plugin-nvidia-gpu-service-test"
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: console-plugin-nvidia-gpu-service-test
      image: quay.io/cilium/alpine-curl:v1.4.0
      imagePullPolicy: "Always"
      args:
        - -XGET
        - --silent
        - --fail
        - --insecure
        - https://console-plugin-nvidia-gpu.nvidia-gpu-operator.svc:9443/plugin-manifest.json
  restartPolicy: Never
MANIFEST:
---
# Source: console-plugin-nvidia-gpu/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: console-plugin-nvidia-gpu
  labels:
    helm.sh/chart: console-plugin-nvidia-gpu-0.2.1
    app.kubernetes.io/name: console-plugin-nvidia-gpu
    app.kubernetes.io/instance: console-plugin-nvidia-gpu
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: console-plugin-nvidia-gpu
    app.kubernetes.io/instance: console-plugin-nvidia-gpu
    app.kubernetes.io/part-of: console-plugin-nvidia-gpu
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: plugin-serving-cert
spec:
  ports:
  - name: 9443-tcp
    protocol: TCP
    port: 9443
    targetPort: 9443
  selector:
    app.kubernetes.io/name: console-plugin-nvidia-gpu
    app.kubernetes.io/instance: console-plugin-nvidia-gpu
  type: ClusterIP
  sessionAffinity: None
---
# Source: console-plugin-nvidia-gpu/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-plugin-nvidia-gpu
  labels:
    helm.sh/chart: console-plugin-nvidia-gpu-0.2.1
    app.kubernetes.io/name: console-plugin-nvidia-gpu
    app.kubernetes.io/instance: console-plugin-nvidia-gpu
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: console-plugin-nvidia-gpu
    app.kubernetes.io/instance: console-plugin-nvidia-gpu
    app.kubernetes.io/part-of: console-plugin-nvidia-gpu
    app.openshift.io/runtime-namespace: console-plugin-nvidia-gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: console-plugin-nvidia-gpu
      app.kubernetes.io/instance: console-plugin-nvidia-gpu
  template:
    metadata:
      labels:
        app.kubernetes.io/name: console-plugin-nvidia-gpu
        app.kubernetes.io/instance: console-plugin-nvidia-gpu
    spec:
      containers:
      - name: console-plugin-nvidia-gpu
        image: "quay.io/edge-infrastructure/console-plugin-nvidia-gpu:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 9443
          protocol: TCP
        volumeMounts:
        - name: plugin-serving-cert
          readOnly: true
          mountPath: /var/serving-cert
        resources:
            {}
      volumes:
      - name: plugin-serving-cert
        secret:
          secretName: plugin-serving-cert
          defaultMode: 420
      - name: nginx-conf
        configMap:
          name: nginx-conf
          defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
# Source: console-plugin-nvidia-gpu/templates/consoleplugin.yaml
apiVersion: console.openshift.io/v1alpha1
kind: ConsolePlugin
metadata:
  name: console-plugin-nvidia-gpu
  labels:
    helm.sh/chart: console-plugin-nvidia-gpu-0.2.1
    app.kubernetes.io/name: console-plugin-nvidia-gpu
    app.kubernetes.io/instance: console-plugin-nvidia-gpu
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: console-plugin-nvidia-gpu
    app.kubernetes.io/instance: console-plugin-nvidia-gpu
    app.kubernetes.io/part-of: console-plugin-nvidia-gpu
spec:
  displayName: 'Console Plugin NVIDIA GPU Template'
  service:
    name: console-plugin-nvidia-gpu
    namespace: nvidia-gpu-operator
    port: 9443
    basePath: '/'
```
